-- Draft-visible Architect Wiki: generated nodes, pages, chunk citations, and history.

alter table files
  add column if not exists needs_wiki boolean not null default true;

create index if not exists files_needs_wiki on files (needs_wiki) where needs_wiki = true;

create table if not exists source_chunks (
  id            uuid primary key default gen_random_uuid(),
  file_id       uuid not null references files(id) on delete cascade,
  source_sha256 text not null,
  chunk_index   integer not null check (chunk_index >= 0),
  content       text not null,
  char_start    integer not null check (char_start >= 0),
  char_end      integer not null check (char_end >= char_start),
  created_at    timestamptz not null default now(),
  unique(file_id, source_sha256, chunk_index)
);

create index if not exists source_chunks_file on source_chunks (file_id, chunk_index);
create index if not exists source_chunks_source on source_chunks (file_id, source_sha256);

create table if not exists wiki_nodes (
  id             uuid primary key default gen_random_uuid(),
  kind           text not null check (
    kind in (
      'source',
      'topic',
      'person',
      'project',
      'area',
      'resource',
      'claim',
      'question',
      'synthesis',
      'contradiction'
    )
  ),
  title          text not null,
  slug           text not null,
  status         text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  summary        text,
  source_file_id uuid references files(id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique(kind, slug)
);

create index if not exists wiki_nodes_status on wiki_nodes (status, updated_at desc);
create index if not exists wiki_nodes_kind on wiki_nodes (kind);
create index if not exists wiki_nodes_source_file on wiki_nodes (source_file_id);

create table if not exists wiki_pages (
  id         uuid primary key default gen_random_uuid(),
  node_id    uuid not null unique references wiki_nodes(id) on delete cascade,
  title      text not null,
  content    text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists wiki_revisions (
  id              uuid primary key default gen_random_uuid(),
  page_id         uuid not null references wiki_pages(id) on delete cascade,
  source_file_id  uuid references files(id) on delete set null,
  revision_number integer not null check (revision_number > 0),
  title           text not null,
  content         text not null,
  reason          text not null default 'Generated by The Architect',
  created_at      timestamptz not null default now(),
  unique(page_id, revision_number)
);

create index if not exists wiki_revisions_page on wiki_revisions (page_id, revision_number desc);
create index if not exists wiki_revisions_source_file on wiki_revisions (source_file_id);

create table if not exists wiki_edges (
  id              uuid primary key default gen_random_uuid(),
  source_node_id  uuid not null references wiki_nodes(id) on delete cascade,
  target_node_id  uuid not null references wiki_nodes(id) on delete cascade,
  type            text not null check (
    type in (
      'derived_from',
      'supports',
      'contradicts',
      'mentions',
      'summarizes',
      'related_to',
      'part_of',
      'answers'
    )
  ),
  status          text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  confidence      float,
  reason          text,
  source_file_id  uuid references files(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique(source_node_id, target_node_id, type, source_file_id)
);

create index if not exists wiki_edges_source on wiki_edges (source_node_id);
create index if not exists wiki_edges_target on wiki_edges (target_node_id);
create index if not exists wiki_edges_status on wiki_edges (status, updated_at desc);
create index if not exists wiki_edges_source_file on wiki_edges (source_file_id);

create table if not exists wiki_citations (
  id          uuid primary key default gen_random_uuid(),
  node_id     uuid references wiki_nodes(id) on delete cascade,
  revision_id uuid references wiki_revisions(id) on delete cascade,
  chunk_id    uuid not null references source_chunks(id) on delete cascade,
  quote       text,
  created_at  timestamptz not null default now(),
  check (node_id is not null or revision_id is not null)
);

create index if not exists wiki_citations_node on wiki_citations (node_id);
create index if not exists wiki_citations_revision on wiki_citations (revision_id);
create index if not exists wiki_citations_chunk on wiki_citations (chunk_id);
